[project]
name = "tele_garmin"
version = "0.1.0"
description = "Telegram bot for Garmin data analysis with AI-powered insights"
authors = ["Developer <dev@example.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.10,<3.13"
pip = "*"

[pypi-dependencies]
# All dependencies managed by pip to avoid conda conflicts
python-telegram-bot = ">=21.0"
garminconnect = "==0.2.25"
anthropic = ">=0.45.0"
langchain = ">=0.2.0"
langchain-openai = ">=0.1.0"
langchain-anthropic = ">=0.1.0"
langchain-community = ">=0.0.20"
langchain-core = ">=0.1.0"
langgraph = ">=0.1.0"
langsmith = ">=0.1.0"
litellm = ">=1.60.0"
numpy = ">=1.24.0"
pandas = ">=2.0.0"
plotly = ">=5.15.0"
cryptography = ">=41.0.0"
python-dotenv = ">=1.0.0"
setuptools = ">=75.0.0"
pytest = ">=7.0.0"
pytest-cov = ">=4.0.0"
pytest-asyncio = ">=0.21.0"
black = ">=23.0.0"
isort = ">=5.12.0"
flake8 = ">=6.0.0"
mypy = ">=1.5.0"
ruff = ">=0.5.0"

[tasks]
# Development tasks
dev = "python main.py"
test = "pytest"
test-cov = "pytest --cov=. --cov-report=term-missing --cov-report=html"
lint = "flake8 ."
lint-ruff = "ruff check ."
ruff-fix = "ruff check --fix ."
format = "black . && isort ."
type-check = "mypy ."

# Bot management
start-dev = { cmd = "python main.py", env = { ENV_FILE = ".env.dev", ENVIRONMENT = "development" } }
start-prod = { cmd = "python main.py", env = { ENV_FILE = ".env", ENVIRONMENT = "production" } }

# Utility scripts
list-users = "python scripts/list_users.py"

# CLI coach interface
coach-cli = "python cli/tele_garmin_cli.py"
coach-init = "python cli/tele_garmin_cli.py --init-config"

[environments]
default = { solve-group = "default" }

[activation]
scripts = ["scripts/setup_env.sh"]