[tool.vulture]
exclude = [
    ".pixi/",
    "pixi.lock", 
    "*.lock",
    "__pycache__/",
    ".git/",
    ".github/",
    "*.pyc"
]
min_confidence = 80
paths = [
    "bot/",
    "core/",
    "services/", 
    "cli/",
    "scripts/",
    "examples/",
    "tests/",
    "main.py"
]