# Garmin AI CLI Configuration Template
# Copy this file and customize for your analysis

# Athlete Information
athlete:
  name: "John Doe"
  email: "john.doe@example.com"  # Garmin Connect email

# Analysis Context
context:
  analysis: |
    Coming back from a minor injury. Focusing on base building and
    avoiding high-intensity work for the next 2 weeks.

  planning: |
    Preparing for Olympic distance triathlon in 12 weeks.
    Priority is building aerobic base and improving run endurance.

# Data Extraction Settings (days to look back)
extraction:
  activities_days: 21      # How many days of activities to extract
  metrics_days: 56         # How many days of metrics to extract
  ai_mode: "standard"      # Overrides .env AI_MODE for coach-cli runs; one of: "development", "standard", "cost_effective"
  enable_plotting: false   # Enable AI-generated plots (default: false to save costs). Set to true for visual insights.

# Upcoming Competitions
competitions:
  - name: "Local Olympic Triathlon"
    date: "2026-04-15"         # YYYY-MM-DD or free-text format (e.g. 'September 2026')
    race_type: "Olympic"
    priority: "A"              # A (highest), B, C priorities
    target_time: "02:30:00"    # HH:MM:SS format

  - name: "Sprint Series Race 1"
    date: "2026-03-20"
    race_type: "Sprint"
    priority: "B"
    target_time: "01:15:00"

outside:
  bikereg:
    - id: 71252               # BikeReg event ID (integer)
      priority: "A"           # Optional; defaults to "B" if omitted
      target_time: "3:00:00"  # Optional; HH:MM:SS

  runreg:
  - url: "https://www.runreg.com/sunflower-relay-half-marathon-and-marathon"
    priority: "B"
    target_time: "3:30:00"

# Output Settings
output:
  directory: "./data"

# Optional: Garmin Credentials (leave empty to use interactive login)
credentials:
  password: ""  # Leave empty for secure interactive input
