name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pixi
        shell: bash
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Pixi version
        run: pixi --version

      - name: Install dependencies
        run: pixi install -q

      - name: Lint (ruff)
        run: pixi run lint-ruff

      - name: Run tests
        run: pixi run test
